menu:
    博文: /blog/
    歸檔: /blog/archives/
    關於: https://kaddopur.github.io/

widgets:
- category
- tag
- tagcloud
- archive

# count
show_count: true
favicon: /blog/images/favicon.ico
logo: /blog/images/logo.png

# Comment
# e.g disqus: seansun
disqus: kaddopur

# Analytics
# google-analytics:
ga: UA-6593436-3

# Copyright Infomation
startyear: 2016
